name: Vue Build

on:
    pull_request:

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
        - name: Checkout code
          uses: actions/checkout@v4

        - name: Set up Node.js
          uses: actions/setup-node@v7

        - name: Install dependencies
          run: npm ci --cache .npm --prefer-offline

        - name: Build project
          run: npm run build
