name: Vue Build

on:
    pull_request:

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
        - name: Checkout code
          uses: actions/checkout@v4

        - name: Set up Node.js
          uses: actions/setup-node@v4

        - name: Install dependencies
          run: npm install

        - name: Lint code
          run: npm run lint

        - name: Build project
          run: npm run build
